import { execSync } from 'child_process';
import { writeFileSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { readFileSync } from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Configuration
const BACKEND_URL = process.env.BACKEND_URL || 'http://localhost:8080';
const OPENAPI_SPEC_URL = `${BACKEND_URL}/v3/api-docs`;
const OUTPUT_DIR = join(__dirname, '../../shared');
const OUTPUT_FILE = join(OUTPUT_DIR, 'api-types.ts');

console.log(`Fetching OpenAPI spec from ${OPENAPI_SPEC_URL}...`);

try {
  // Fetch the OpenAPI spec
  const response = await fetch(OPENAPI_SPEC_URL);
  if (!response.ok) {
    throw new Error(`Failed to fetch OpenAPI spec: ${response.status} ${response.statusText}`);
  }
  
  const openApiSpec = await response.json();
  
  // Save the raw spec to a temporary file
  const tempSpecFile = join(__dirname, '../../shared/openapi-spec.json');
  mkdirSync(OUTPUT_DIR, { recursive: true });
  writeFileSync(tempSpecFile, JSON.stringify(openApiSpec, null, 2), 'utf-8');
  
  console.log('OpenAPI spec fetched and saved. Generating TypeScript types...');
  
  // Generate TypeScript types using openapi-typescript
  try {
    const types = execSync(
      `npx --yes openapi-typescript "${tempSpecFile}" --output "${OUTPUT_FILE}"`,
      { encoding: 'utf-8', cwd: join(__dirname, '../') }
    );
    
    console.log('TypeScript types generated successfully!');
    console.log(`Types saved to: ${OUTPUT_FILE}`);
    
    // Read the generated file and add a header comment
    const generatedContent = readFileSync(OUTPUT_FILE, 'utf-8');
    const header = `/**
 * This file is auto-generated from the OpenAPI specification.
 * Do not edit this file manually. Instead, run: npm run generate:types
 * 
 * Generated from: ${OPENAPI_SPEC_URL}
 * Generated at: ${new Date().toISOString()}
 */

`;
    
    writeFileSync(OUTPUT_FILE, header + generatedContent, 'utf-8');
    
    console.log('✅ Type generation complete!');
  } catch (error) {
    console.error('Error generating types:', error.message);
    process.exit(1);
  }
} catch (error) {
  console.error('Error fetching OpenAPI spec:', error.message);
  console.error('\nMake sure the backend is running and accessible at:', BACKEND_URL);
  console.error('You can set a custom backend URL with: BACKEND_URL=http://your-backend-url npm run generate:types');
  process.exit(1);
}

