/**
 * This file is auto-generated from the OpenAPI specification.
 * Do not edit this file manually. Instead, run: npm run generate:types
 * 
 * Generated from: http://localhost:8080/v3/api-docs
 * Generated at: 2025-12-27T18:08:06.826Z
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/bookmarks/{id}": {
    /**
     * Get bookmark by ID
     * @description Retrieve a specific bookmark by its ID
     */
    get: operations["getBookmarkById"];
    /**
     * Update a bookmark
     * @description Update an existing bookmark by its ID
     */
    put: operations["updateBookmark"];
    /**
     * Delete a bookmark
     * @description Delete a bookmark by its ID
     */
    delete: operations["deleteBookmark"];
  };
  "/api/bookmarks": {
    /**
     * Get all bookmarks
     * @description Retrieve a list of all bookmarks
     */
    get: operations["getAllBookmarks"];
    /**
     * Create a new bookmark
     * @description Create a new bookmark with the provided details
     */
    post: operations["createBookmark"];
  };
  "/api/bookmarks/search": {
    /**
     * Search bookmarks
     * @description Search bookmarks by title (case-insensitive)
     */
    get: operations["searchBookmarks"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description Bookmark details to create */
    BookmarkRequestDTO: {
      /**
       * @description Title of the bookmark
       * @example Spring Boot Documentation
       */
      title: string;
      /**
       * @description URL of the bookmark
       * @example https://spring.io/projects/spring-boot
       */
      url: string;
      /**
       * @description Description of the bookmark
       * @example Official Spring Boot documentation
       */
      description?: string;
    };
    /** @description Response DTO for bookmark data */
    BookmarkResponseDTO: {
      /**
       * Format: int64
       * @description Unique identifier of the bookmark
       * @example 1
       */
      id?: number;
      /**
       * @description Title of the bookmark
       * @example Spring Boot Documentation
       */
      title?: string;
      /**
       * @description URL of the bookmark
       * @example https://spring.io/projects/spring-boot
       */
      url?: string;
      /**
       * @description Description of the bookmark
       * @example Official Spring Boot documentation
       */
      description?: string;
      /**
       * Format: date-time
       * @description Timestamp when the bookmark was created
       */
      createdAt?: string;
      /**
       * Format: date-time
       * @description Timestamp when the bookmark was last updated
       */
      updatedAt?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Get bookmark by ID
   * @description Retrieve a specific bookmark by its ID
   */
  getBookmarkById: {
    parameters: {
      path: {
        /**
         * @description ID of the bookmark to retrieve
         * @example 1
         */
        id: number;
      };
    };
    responses: {
      /** @description Bookmark found */
      200: {
        content: {
          "application/json": components["schemas"]["BookmarkResponseDTO"];
        };
      };
      /** @description Bookmark not found */
      404: {
        content: {
          "*/*": components["schemas"]["BookmarkResponseDTO"];
        };
      };
    };
  };
  /**
   * Update a bookmark
   * @description Update an existing bookmark by its ID
   */
  updateBookmark: {
    parameters: {
      path: {
        /**
         * @description ID of the bookmark to update
         * @example 1
         */
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BookmarkRequestDTO"];
      };
    };
    responses: {
      /** @description Bookmark updated successfully */
      200: {
        content: {
          "application/json": components["schemas"]["BookmarkResponseDTO"];
        };
      };
      /** @description Invalid input data */
      400: {
        content: {
          "*/*": components["schemas"]["BookmarkResponseDTO"];
        };
      };
      /** @description Bookmark not found */
      404: {
        content: {
          "*/*": components["schemas"]["BookmarkResponseDTO"];
        };
      };
    };
  };
  /**
   * Delete a bookmark
   * @description Delete a bookmark by its ID
   */
  deleteBookmark: {
    parameters: {
      path: {
        /**
         * @description ID of the bookmark to delete
         * @example 1
         */
        id: number;
      };
    };
    responses: {
      /** @description Bookmark deleted successfully */
      204: {
        content: never;
      };
      /** @description Bookmark not found */
      404: {
        content: never;
      };
    };
  };
  /**
   * Get all bookmarks
   * @description Retrieve a list of all bookmarks
   */
  getAllBookmarks: {
    responses: {
      /** @description Successfully retrieved list of bookmarks */
      200: {
        content: {
          "application/json": components["schemas"]["BookmarkResponseDTO"];
        };
      };
    };
  };
  /**
   * Create a new bookmark
   * @description Create a new bookmark with the provided details
   */
  createBookmark: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["BookmarkRequestDTO"];
      };
    };
    responses: {
      /** @description Bookmark created successfully */
      201: {
        content: {
          "application/json": components["schemas"]["BookmarkResponseDTO"];
        };
      };
      /** @description Invalid input data */
      400: {
        content: {
          "*/*": components["schemas"]["BookmarkResponseDTO"];
        };
      };
    };
  };
  /**
   * Search bookmarks
   * @description Search bookmarks by title (case-insensitive)
   */
  searchBookmarks: {
    parameters: {
      query: {
        /**
         * @description Search query string
         * @example spring
         */
        q: string;
      };
    };
    responses: {
      /** @description Successfully retrieved matching bookmarks */
      200: {
        content: {
          "application/json": components["schemas"]["BookmarkResponseDTO"];
        };
      };
    };
  };
}
